controller_list:
  - name: fake_testing_rig_controller
    type: $(arg fake_execution_type)
    joints:
      - outer_ring
      - middle_ring
      - inner_ring
initial:  # Define initial robot poses per group
#  - group: testing_rig
#    pose: home

  []