testing_rig_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - outer_ring
    - middle_ring
    - inner_ring
    # - Beacon
  gains:
    outer_ring:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    middle_ring:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    inner_ring:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    # Beacon:
    #   p: 100
    #   d: 1
    #   i: 1
    #   i_clamp: 1