controller_list:
  - name: testing_rig_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - outer_ring
      - middle_ring
      - inner_ring
      # - Beacon