arm1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder
    - elbow_1
    - elbow_2
    - wrist
  gains:
    shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1