controller_list:
  - name: arm1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder
      - elbow_1
      - elbow_2
      - wrist